package avl_tree_labed2;

import javax.swing.JOptionPane;

public class AnimationWindow extends javax.swing.JFrame {

    /**
     * Creates new form AnimationWindow
     */
    SelfBalancingBinarySearchTree tree;
    Animation animacion;
    public static String resultado;

    public AnimationWindow() {
        initComponents();
        resultado = "";
        tree = new SelfBalancingBinarySearchTree();
        animacion = new Animation(tree);
        animacion.setBounds(400, 0, this.getWidth() - 400, this.getHeight());
        this.add(animacion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDato = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnInsertar = new javax.swing.JButton();
        emptybtn = new javax.swing.JButton();
        btnaltura = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnporniveles = new javax.swing.JButton();
        btninorden = new javax.swing.JButton();
        btnpreorden = new javax.swing.JButton();
        btnpostorden = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultadotxt = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        btneliminar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(null);

        contentPanel.setBackground(new java.awt.Color(21, 61, 121));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("AVL Tree");

        txtDato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDatoKeyTyped(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/searchImg.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.setPreferredSize(new java.awt.Dimension(140, 40));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnInsertar.setBackground(new java.awt.Color(255, 255, 255));
        btnInsertar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnInsertar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/insertImg.png"))); // NOI18N
        btnInsertar.setText("insertar");
        btnInsertar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        emptybtn.setBackground(new java.awt.Color(255, 255, 255));
        emptybtn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        emptybtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/emptyImg.png"))); // NOI18N
        emptybtn.setText("Vaciar");
        emptybtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        emptybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emptybtnActionPerformed(evt);
            }
        });

        btnaltura.setBackground(new java.awt.Color(255, 255, 255));
        btnaltura.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnaltura.setText("Altura");
        btnaltura.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnaltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnalturaActionPerformed(evt);
            }
        });

        btneliminar.setBackground(new java.awt.Color(255, 255, 255));
        btneliminar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/deleteImg.png"))); // NOI18N
        btneliminar.setText("Eliminar");
        btneliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btnporniveles.setBackground(new java.awt.Color(255, 255, 255));
        btnporniveles.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnporniveles.setText("Por niveles");
        btnporniveles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnporniveles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpornivelesActionPerformed(evt);
            }
        });

        btninorden.setBackground(new java.awt.Color(255, 255, 255));
        btninorden.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btninorden.setText("Inorden");
        btninorden.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btninorden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninordenActionPerformed(evt);
            }
        });

        btnpreorden.setBackground(new java.awt.Color(255, 255, 255));
        btnpreorden.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnpreorden.setText("preOrden");
        btnpreorden.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnpreorden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpreordenActionPerformed(evt);
            }
        });

        btnpostorden.setBackground(new java.awt.Color(255, 255, 255));
        btnpostorden.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnpostorden.setText("posOrden");
        btnpostorden.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnpostorden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpostordenActionPerformed(evt);
            }
        });

        resultadotxt.setEditable(false);
        resultadotxt.setColumns(20);
        resultadotxt.setRows(5);
        jScrollPane1.setViewportView(resultadotxt);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 371, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        btneliminar1.setBackground(new java.awt.Color(255, 255, 255));
        btneliminar1.setFont(new java.awt.Font("Roboto", 1, 10)); // NOI18N
        btneliminar1.setText("Borrar");
        btneliminar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btneliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel1))
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contentPanelLayout.createSequentialGroup()
                                .addComponent(txtDato, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(emptybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(contentPanelLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnaltura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(23, 23, 23)
                                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnInsertar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btneliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))))))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btneliminar1)
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btninorden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnpostorden, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnporniveles, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnpreorden, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDato, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emptybtn))
                .addGap(31, 31, 31)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnaltura, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btneliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btninorden, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnporniveles, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnpostorden, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpreorden, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btneliminar1)
                .addGap(58, 58, 58))
        );

        getContentPane().add(contentPanel);
        contentPanel.setBounds(0, 0, 400, 720);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void setResultadotxt(String s) {
        resultadotxt.append(s);
    }
    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        // TODO add your handling code here:  
        if (!txtDato.getText().equals("")) {
            tree.insert(Integer.parseInt(txtDato.getText()));
        } else {
            JOptionPane.showMessageDialog(null, "Verifique el dato");
        }

    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btninordenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninordenActionPerformed
        // TODO add your handling code here:        
        resultado = "";
        tree.inorder();
        resultadotxt.append("\nInorden: " + resultado);

    }//GEN-LAST:event_btninordenActionPerformed

    private void btnpostordenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpostordenActionPerformed
        // TODO add your handling code here:
        resultado = "";
        tree.postorder();
        resultadotxt.append("\nPost orden: " + resultado);

    }//GEN-LAST:event_btnpostordenActionPerformed

    private void btnpreordenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpreordenActionPerformed
        // TODO add your handling code here:
        resultado = "";
        tree.preorder();
        resultadotxt.append("\nPre orden: " + resultado);
    }//GEN-LAST:event_btnpreordenActionPerformed

    private void btnpornivelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpornivelesActionPerformed
        // TODO add your handling code here:
        resultado = "";
        if(!tree.isEmpty())
            tree.PorNivelesRec();
        resultadotxt.append("\nPor niveles: " + resultado);
    }//GEN-LAST:event_btnpornivelesActionPerformed

    private void txtDatoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDatoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtDatoKeyTyped

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        if (!txtDato.getText().equals("")) {
            if (tree.search(Integer.parseInt(txtDato.getText()))) {
                JOptionPane.showMessageDialog(null, "Sí se encontró el nodo");
            } else {
                JOptionPane.showMessageDialog(null, "NO se encontró el nodo");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Verifique el dato");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnalturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnalturaActionPerformed
        // TODO add your handling code here:
        if (!txtDato.getText().equals("")) {
            resultado = "";
            if (tree.search(Integer.parseInt(txtDato.getText()))) {
                resultadotxt.append("\nLa altura del nodo " + txtDato.getText() + " es: " + resultado);
            } else {
                JOptionPane.showMessageDialog(null, "NO se encontró el nodo");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Verifique el dato");
        }
    }//GEN-LAST:event_btnalturaActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here
        if (!txtDato.getText().equals("")) {
            tree.delete(Integer.parseInt(txtDato.getText()));
        } else {
            JOptionPane.showMessageDialog(null, "Verifique el dato");
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void emptybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emptybtnActionPerformed
        // TODO add your handling code here:
        tree.clear();
    }//GEN-LAST:event_emptybtnActionPerformed

    private void btneliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminar1ActionPerformed
        // TODO add your handling code here:
        resultadotxt.setText("");
    }//GEN-LAST:event_btneliminar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnimationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnimationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnimationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnimationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnimationWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnaltura;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btneliminar1;
    private javax.swing.JButton btninorden;
    private javax.swing.JButton btnporniveles;
    private javax.swing.JButton btnpostorden;
    private javax.swing.JButton btnpreorden;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton emptybtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea resultadotxt;
    private javax.swing.JTextField txtDato;
    // End of variables declaration//GEN-END:variables
}
